version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bot_db
    ports:
      - "5432:5432"
#      - "8080:8080"
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data

